name: Gradle Build

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew buildPlugin
        env:
          ORG_GRADLE_PROJECT_pluginVersion: 0.1-DEV
      - name: Build and Sign
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew signPlugin
        env:
          ORG_GRADLE_PROJECT_pluginVersion: ${{ github.ref_name }}
          CERTIFICATE_CHAIN: ${{ secrets.SIGNING_CERTIFICATE }}
          PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          prerelease: false
          files: |
            build/distributions/*-signed.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/distributions/
          if-no-files-found: error